import jsPDF from 'jspdf';

export function generateProjectDocPDF() {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  let y = 40;
  doc.setFontSize(18);
  doc.text('Smart Dine POS (Point of Sale System) – Project Documentation', 40, y);
  y += 30;
  doc.setFontSize(12);
  doc.text('Overview:', 40, y);
  y += 18;
  doc.text('Smart Dine POS is a modern Point of Sale System designed to streamline restaurant operations. The project features a modern React frontend and is ready for integration with a PHP Laravel backend. It supports role-based access, order management, menu management, billing (with invoice PDF generation), analytics, inventory, reservations, and more.', 40, y, { maxWidth: 520 });
  y += 60;
  doc.text('Frontend:', 40, y);
  y += 18;
  doc.text('- React, Redux Toolkit, Tailwind CSS, Vite, jsPDF, Lucide-react', 60, y);
  y += 18;
  doc.text('- Role-based access, billing & invoicing, order/menu management, analytics, inventory, reservations, settings, user management', 60, y, { maxWidth: 500 });
  y += 36;
  doc.text('Backend (Recommended: PHP Laravel):', 40, y);
  y += 18;
  doc.text('- Laravel 10+, MySQL/PostgreSQL/SQLite, RESTful API, Auth (Breeze/Jetstream/Sanctum)', 60, y, { maxWidth: 500 });
  y += 36;
  doc.text('How to Run (Frontend):', 40, y);
  y += 18;
  doc.text('1. npm install', 60, y);
  y += 18;
  doc.text('2. npm run dev', 60, y);
  y += 18;
  doc.text('3. Open http://localhost:5173', 60, y);
  y += 36;
  doc.text('How to Run (Backend – Laravel):', 40, y);
  y += 18;
  doc.text('1. composer create-project laravel/laravel backend', 60, y);
  y += 18;
  doc.text('2. Configure .env', 60, y);
  y += 18;
  doc.text('3. php artisan migrate', 60, y);
  y += 18;
  doc.text('4. php artisan serve', 60, y);
  y += 18;
  doc.text('5. API: http://localhost:8000/api', 60, y);
  y += 36;
  doc.text('Integration:', 40, y);
  y += 18;
  doc.text('- React frontend communicates with Laravel backend via RESTful APIs.', 60, y, { maxWidth: 500 });
  y += 18;
  doc.text('- Update src/services/api.js with backend API base URL.', 60, y, { maxWidth: 500 });
  y += 18;
  doc.text('- Use JWT or Sanctum for secure API authentication.', 60, y, { maxWidth: 500 });
  y += 36;
  doc.text('Deployment:', 40, y);
  y += 18;
  doc.text('- Frontend: Netlify, Vercel, or static hosting.', 60, y);
  y += 18;
  doc.text('- Backend: Shared hosting, VPS, or cloud.', 60, y);
  y += 36;
  doc.text('Customization & Extension:', 40, y);
  y += 18;
  doc.text('- Add new modules/components and Redux slices.', 60, y);
  y += 18;
  doc.text('- Extend backend with new models, migrations, controllers.', 60, y);
  y += 18;
  doc.text('- Update API endpoints and connect in api.js.', 60, y);
  y += 36;
  doc.text('Contributors:', 40, y);
  y += 18;
  doc.text('- Project Owner: Bandhan203', 60, y);
  y += 18;
  doc.text('- Frontend: React, Redux, Tailwind, jsPDF', 60, y);
  y += 18;
  doc.text('- Backend: PHP Laravel (recommended)', 60, y);
  y += 36;
  doc.text('License:', 40, y);
  y += 18;
  doc.text('This project is for educational and demonstration purposes. For production use, review and update security, authentication, and data validation.', 60, y, { maxWidth: 500 });
  doc.save('My_RMS_Project_Documentation.pdf');
}
