CREATE TABLE bills (
    id bigint unsigned NOT NULL AUTO_INCREMENT,
    bill_number varchar(255) NOT NULL UNIQUE,
    order_id bigint unsigned NOT NULL,
    customer_name varchar(255) NOT NULL,
    customer_email varchar(255) NULL,
    customer_phone varchar(255) NULL,
    table_number varchar(255) NULL,
    order_type enum('dine-in', 'pickup', 'delivery') DEFAULT 'dine-in',
    subtotal decimal(10,2) NOT NULL,
    tax_rate decimal(5,2) DEFAULT 8.00,
    tax_amount decimal(10,2) NOT NULL,
    discount_amount decimal(10,2) DEFAULT 0.00,
    service_charge decimal(10,2) DEFAULT 0.00,
    total_amount decimal(10,2) NOT NULL,
    payment_method enum('cash', 'card', 'digital', 'bank_transfer') DEFAULT 'cash',
    payment_status enum('pending', 'paid', 'partially_paid', 'refunded') DEFAULT 'pending',
    paid_amount decimal(10,2) DEFAULT 0.00,
    change_amount decimal(10,2) DEFAULT 0.00,
    payment_date timestamp NULL,
    payment_reference varchar(255) NULL,
    notes text NULL,
    waiter_name varchar(255) NULL,
    created_by bigint unsigned NULL,
    is_printed boolean DEFAULT false,
    printed_at timestamp NULL,
    status enum('draft', 'generated', 'paid', 'cancelled', 'refunded') DEFAULT 'draft',
    created_at timestamp NULL,
    updated_at timestamp NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
